version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: toadoo-backend
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic:/app/alembic
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/toadoo.db:/app/toadoo.db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on: []

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: toadoo-frontend
    env_file:
      - ./frontend/.env
    expose:
      - "5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: toadoo-nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"

networks:
  default:
    name: toadoo-network
