"""Add total_completed_count to users

Revision ID: 5243e3c7a9c7
Revises: 28907f53438a
Create Date: 2025-10-08 16:07:58.842034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5243e3c7a9c7'
down_revision: Union[str, None] = '28907f53438a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_completed_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_completed_count')
    # ### end Alembic commands ###
